Update cicd_flow.yml

diff --git a/.github/workflows/cicd_flow.yml b/.github/workflows/cicd_flow.yml
--- a/.github/workflows/cicd_flow.yml
+++ b/.github/workflows/cicd_flow.yml
@@ -108,6 +108,27 @@ jobs:
                   }
                   EOF
                   sudo systemctl restart nginx
+    Health-Check: 
+      needs:
+        - CD
+      runs-on: ubuntu-latest
+      steps:
+            - name: Check Health Status
+              run: |
+                echo "Checking health status"
+                for i in {1..5}; do
+                  HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" http://${{ secrets.SERVER_HOST }})
+                  if [ $HTTP_STATUS -eq 200 ]; then
+                    echo "Health check passed"
+                    exit 0
+                  fi
+                  sleep 5
+                done
+                if [ $? -ne 0 ]; then
+                  echo "Health check failed after 5 attempts"
+                  exit 1
+                fi
+              
               
 
 
